
services:
  - type: web
    name: crazy-v3
    env: node
    repo: https://github.com/Johnwayne209/John Reese
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
```